### ISSUE TITLE
Any examples of loopback-testing usage?

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-testing#36]
Are the examples in "building test data" and "basic usage" meant to be used together or are they completely different concepts? In strongloop/looback itself, I couldn't find any references for `TestDataBuilder` so here should I be looking to learn by example?

**Comment by jrschumacher** [comment]
Working on adding tests to strongloop/loopback-example-full-stack see strongloop/loopback-example-full-stack/pull/53
