### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback-testing#65]
Please create a simple readme with the all helpers and some examples how to use it

**Comment by Swatto** [comment]
:+1:

**Comment by bistmaster** [comment]
+1

**Comment by ianseyer** [comment]
+1

**Comment by yagop** [comment]
:+1:

**Comment by TimPerry** [comment]
+1

**Comment by JumBay** [comment]
+1

**Comment by danieltrautmann** [comment]
+1

**Comment by GuillaumeLeclerc** [comment]
+1, I mean it's not usable at all.

**Comment by Shyri** [comment]
+1

**Comment by dtomasi** [comment]
+1

**Comment by rleira** [comment]
:+1:

**Comment by superkhau** [comment]
Hey everyone, we are in the process of deprecating loopback-testing. This means this repo will be removed and archived. It has been decided the headaches of maintaining this repo is not worth the effort when there are better tools for the tasks provided by this repo. Sorry for any inconvenience this may cause. I will be posting an official announcement on the Google Groups (stickied) soon.

**Comment by rkmax** [comment]
I made a helper for use loopback with supertest https://www.npmjs.com/package/loopback-testing-helpers. it's fairly simple
