### ISSUE TITLE
Documentation incorrect ?

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [strongloop/loopback-testing#70]
Hello,

I followed exactly the documentation (I want to use a local mocha) and this file does not exists `./node_modules/loopback-testing/node_modules/.bin/mocha`, I had to go into `node_modules/loopback-testing` and run `npm install` there. I think the documentation might need to be updated to add this required step or maybe I did something wrong ? 

Bets regards,

Guillaume Leclerc

**Comment by roychoo** [comment]
i think is because you already have mocha installed as part of project dependencies.

**Comment by GuillaumeLeclerc** [comment]
It is true, but i still find it a little misleading.

**Comment by superkhau** [comment]
@crandmck Maybe we can make this more clear?

**Comment by crandmck** [comment]
@superkhau I didn't write this doc and I haven't worked on it at all.   Can you please find someone else to handle it?  In general, testing _should_ be a part of the docs, but there is currently more work than I can do, so if someone in QA or dev could take this, I would appreciate it.

**Comment by superkhau** [comment]
@crandmck We can definitely plan this for someone on the triage team to handle. Let's get one of our people to comment here for best practices and then you can simply copy it the official docs.
